# Generated by Django 4.2.4 on 2023-10-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_review", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="chef",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
